<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-3L2FMR8" failures="3" tests="4" name="rerunfail_Test" time="0.055" errors="0" timestamp="3 Aug 2024 18:08:08 GMT">
  <testcase classname="rerun_fail_while_exe" name="f1" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rerun_fail_while_exe.f1(rerun_fail_while_exe.java:13)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase classname="rerun_fail_while_exe" name="f2" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rerun_fail_while_exe.f2(rerun_fail_while_exe.java:19)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
  <testcase classname="rerun_fail_while_exe" name="f3" time="0.002"/>
  <testcase classname="rerun_fail_while_exe" name="f4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rerun_fail_while_exe.f4(rerun_fail_while_exe.java:31)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f4 -->
</testsuite> <!-- rerunfail_Test -->
